// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/knowledge_base/data/models/document_chunk.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 5223394885310789055),
      name: 'DocumentChunk',
      lastPropertyId: const obx_int.IdUid(10, 8130805105756419040),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3577883487304066986),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7306441967964954554),
            name: 'knowledgeBaseId',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(1, 3444487793486496398)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 839274327261406433),
            name: 'fileId',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(2, 4285884287700572619)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8246295538068848275),
            name: 'fileName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7220381253573396853),
            name: 'content',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8286490410586914452),
            name: 'chunkIndex',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3270084579822756663),
            name: 'startOffset',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 1389327890513774596),
            name: 'endOffset',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 1523656462238500495),
            name: 'embedding',
            type: 28,
            flags: 8,
            indexId: const obx_int.IdUid(3, 3559951831518984257),
            hnswParams: obx_int.ModelHnswParams(
              dimensions: 1536,
            )),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 8130805105756419040),
            name: 'createdAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 5119917487914971180),
      name: 'DocumentChunkLarge',
      lastPropertyId: const obx_int.IdUid(10, 521043241246943084),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4346819707574845755),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4250388590584957285),
            name: 'knowledgeBaseId',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(4, 141613674861393567)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1936039374186638845),
            name: 'fileId',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(5, 6642736147652486392)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4423883388941324703),
            name: 'fileName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 47592562653720438),
            name: 'content',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6639506184699925094),
            name: 'chunkIndex',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2907320335715403867),
            name: 'startOffset',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 2760812362991707687),
            name: 'endOffset',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 4432577616893063344),
            name: 'embedding',
            type: 28,
            flags: 8,
            indexId: const obx_int.IdUid(6, 2964111997118327839),
            hnswParams: obx_int.ModelHnswParams(
              dimensions: 3072,
            )),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 521043241246943084),
            name: 'createdAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 5119917487914971180),
      lastIndexId: const obx_int.IdUid(6, 2964111997118327839),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    DocumentChunk: obx_int.EntityDefinition<DocumentChunk>(
        model: _entities[0],
        toOneRelations: (DocumentChunk object) => [],
        toManyRelations: (DocumentChunk object) => {},
        getId: (DocumentChunk object) => object.id,
        setId: (DocumentChunk object, int id) {
          object.id = id;
        },
        objectToFB: (DocumentChunk object, fb.Builder fbb) {
          final knowledgeBaseIdOffset = fbb.writeString(object.knowledgeBaseId);
          final fileIdOffset = fbb.writeString(object.fileId);
          final fileNameOffset = fbb.writeString(object.fileName);
          final contentOffset = fbb.writeString(object.content);
          final embeddingOffset = object.embedding == null
              ? null
              : fbb.writeListFloat32(object.embedding!);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, knowledgeBaseIdOffset);
          fbb.addOffset(2, fileIdOffset);
          fbb.addOffset(3, fileNameOffset);
          fbb.addOffset(4, contentOffset);
          fbb.addInt64(5, object.chunkIndex);
          fbb.addInt64(6, object.startOffset);
          fbb.addInt64(7, object.endOffset);
          fbb.addOffset(8, embeddingOffset);
          fbb.addInt64(9, object.createdAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = DocumentChunk()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..knowledgeBaseId = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..fileId = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..fileName = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..content = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..chunkIndex =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0)
            ..startOffset =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16)
            ..endOffset =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 18)
            ..embedding =
                const fb.ListReader<double>(fb.Float32Reader(), lazy: false)
                    .vTableGetNullable(buffer, rootOffset, 20)
            ..createdAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0));

          return object;
        }),
    DocumentChunkLarge: obx_int.EntityDefinition<DocumentChunkLarge>(
        model: _entities[1],
        toOneRelations: (DocumentChunkLarge object) => [],
        toManyRelations: (DocumentChunkLarge object) => {},
        getId: (DocumentChunkLarge object) => object.id,
        setId: (DocumentChunkLarge object, int id) {
          object.id = id;
        },
        objectToFB: (DocumentChunkLarge object, fb.Builder fbb) {
          final knowledgeBaseIdOffset = fbb.writeString(object.knowledgeBaseId);
          final fileIdOffset = fbb.writeString(object.fileId);
          final fileNameOffset = fbb.writeString(object.fileName);
          final contentOffset = fbb.writeString(object.content);
          final embeddingOffset = object.embedding == null
              ? null
              : fbb.writeListFloat32(object.embedding!);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, knowledgeBaseIdOffset);
          fbb.addOffset(2, fileIdOffset);
          fbb.addOffset(3, fileNameOffset);
          fbb.addOffset(4, contentOffset);
          fbb.addInt64(5, object.chunkIndex);
          fbb.addInt64(6, object.startOffset);
          fbb.addInt64(7, object.endOffset);
          fbb.addOffset(8, embeddingOffset);
          fbb.addInt64(9, object.createdAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = DocumentChunkLarge()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..knowledgeBaseId = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..fileId = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..fileName = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..content = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..chunkIndex =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0)
            ..startOffset =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16)
            ..endOffset =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 18)
            ..embedding =
                const fb.ListReader<double>(fb.Float32Reader(), lazy: false)
                    .vTableGetNullable(buffer, rootOffset, 20)
            ..createdAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0));

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [DocumentChunk] entity fields to define ObjectBox queries.
class DocumentChunk_ {
  /// See [DocumentChunk.id].
  static final id =
      obx.QueryIntegerProperty<DocumentChunk>(_entities[0].properties[0]);

  /// See [DocumentChunk.knowledgeBaseId].
  static final knowledgeBaseId =
      obx.QueryStringProperty<DocumentChunk>(_entities[0].properties[1]);

  /// See [DocumentChunk.fileId].
  static final fileId =
      obx.QueryStringProperty<DocumentChunk>(_entities[0].properties[2]);

  /// See [DocumentChunk.fileName].
  static final fileName =
      obx.QueryStringProperty<DocumentChunk>(_entities[0].properties[3]);

  /// See [DocumentChunk.content].
  static final content =
      obx.QueryStringProperty<DocumentChunk>(_entities[0].properties[4]);

  /// See [DocumentChunk.chunkIndex].
  static final chunkIndex =
      obx.QueryIntegerProperty<DocumentChunk>(_entities[0].properties[5]);

  /// See [DocumentChunk.startOffset].
  static final startOffset =
      obx.QueryIntegerProperty<DocumentChunk>(_entities[0].properties[6]);

  /// See [DocumentChunk.endOffset].
  static final endOffset =
      obx.QueryIntegerProperty<DocumentChunk>(_entities[0].properties[7]);

  /// See [DocumentChunk.embedding].
  static final embedding =
      obx.QueryHnswProperty<DocumentChunk>(_entities[0].properties[8]);

  /// See [DocumentChunk.createdAt].
  static final createdAt =
      obx.QueryDateProperty<DocumentChunk>(_entities[0].properties[9]);
}

/// [DocumentChunkLarge] entity fields to define ObjectBox queries.
class DocumentChunkLarge_ {
  /// See [DocumentChunkLarge.id].
  static final id =
      obx.QueryIntegerProperty<DocumentChunkLarge>(_entities[1].properties[0]);

  /// See [DocumentChunkLarge.knowledgeBaseId].
  static final knowledgeBaseId =
      obx.QueryStringProperty<DocumentChunkLarge>(_entities[1].properties[1]);

  /// See [DocumentChunkLarge.fileId].
  static final fileId =
      obx.QueryStringProperty<DocumentChunkLarge>(_entities[1].properties[2]);

  /// See [DocumentChunkLarge.fileName].
  static final fileName =
      obx.QueryStringProperty<DocumentChunkLarge>(_entities[1].properties[3]);

  /// See [DocumentChunkLarge.content].
  static final content =
      obx.QueryStringProperty<DocumentChunkLarge>(_entities[1].properties[4]);

  /// See [DocumentChunkLarge.chunkIndex].
  static final chunkIndex =
      obx.QueryIntegerProperty<DocumentChunkLarge>(_entities[1].properties[5]);

  /// See [DocumentChunkLarge.startOffset].
  static final startOffset =
      obx.QueryIntegerProperty<DocumentChunkLarge>(_entities[1].properties[6]);

  /// See [DocumentChunkLarge.endOffset].
  static final endOffset =
      obx.QueryIntegerProperty<DocumentChunkLarge>(_entities[1].properties[7]);

  /// See [DocumentChunkLarge.embedding].
  static final embedding =
      obx.QueryHnswProperty<DocumentChunkLarge>(_entities[1].properties[8]);

  /// See [DocumentChunkLarge.createdAt].
  static final createdAt =
      obx.QueryDateProperty<DocumentChunkLarge>(_entities[1].properties[9]);
}
